-- MUTUAL – seed: 162 deutschsprachige Karten (9 je Kategorie).
-- Formulierungen: klar, respektvoll, genderinklusiv, erwachsen, nicht pornografisch.
-- allowed_roles wird nach dem Insert anhand des role_model gesetzt.

insert into public.question_cards
  (slug, title, prompt, category, intensity_level, risk_level, role_model, safety_note, requires_safety_confirmation)
values
-- ── Nähe und Atmosphäre ────────────────────────────────────────────────────
('na-01','Langsames Ankommen','Bewusst Zeit nehmen, um erst einmal nur anzukommen: Nähe ohne Ziel, ohne Erwartung.','naehe_atmosphaere',1,'low','symmetric',null,false),
('na-02','Licht und Stimmung','Gemeinsam eine Atmosphäre gestalten, die euch beiden gefällt: gedämpftes Licht, Musik, Wärme.','naehe_atmosphaere',1,'low','symmetric',null,false),
('na-03','Lange Umarmung','Eine Umarmung, die so lange dauert, bis beide wirklich loslassen wollen.','naehe_atmosphaere',1,'low','symmetric',null,false),
('na-04','Nähe ohne Worte','Eine Weile bewusst schweigend beieinander sein und nur über Berührung kommunizieren.','naehe_atmosphaere',1,'low','symmetric',null,false),
('na-05','Gemeinsames Bad','Zusammen baden oder duschen, ohne dass daraus mehr werden muss.','naehe_atmosphaere',2,'low','symmetric',null,false),
('na-06','Ein Abend nur für euch','Einen ganzen Abend ohne Handy, ohne Verpflichtungen, nur füreinander reservieren.','naehe_atmosphaere',1,'low','symmetric',null,false),
('na-07','Einschlafen in Kontakt','Bewusst in Körperkontakt einschlafen, auch wenn es unbequemer ist als gewohnt.','naehe_atmosphaere',1,'low','symmetric',null,false),
('na-08','Rituale der Nähe','Ein kleines wiederkehrendes Ritual entwickeln, das nur euch beiden gehört.','naehe_atmosphaere',1,'low','symmetric',null,false),
('na-09','Nähe nach Streit','Nach einem Konflikt bewusst körperliche Nähe suchen, sobald beide dazu bereit sind.','naehe_atmosphaere',2,'low','symmetric',null,false),
-- ── Kommunikation ──────────────────────────────────────────────────────────
('ko-01','Wünsche laut aussprechen','Während intimer Momente sagen, was sich gerade gut anfühlt und was du dir wünschst.','kommunikation',2,'low','symmetric',null,false),
('ko-02','Nachfragen üben','Aktiv nachfragen, bevor etwas Neues passiert – und ein Nein selbstverständlich stehen lassen.','kommunikation',1,'low','symmetric',null,false),
('ko-03','Ampel-Signale','Ein einfaches Signalsystem vereinbaren, mit dem ihr jederzeit Tempo und Grenzen anzeigen könnt.','kommunikation',1,'low','symmetric',null,false),
('ko-04','Erregung beschreiben','Der anderen Person in Worten beschreiben, was du gerade empfindest.','kommunikation',3,'low','symmetric',null,false),
('ko-05','Feedback danach','Nach intimen Momenten kurz austauschen, was besonders schön war.','kommunikation',1,'low','symmetric',null,false),
('ko-06','Über Fantasien sprechen','Einander eine Fantasie erzählen, ohne dass daraus eine Verpflichtung entsteht.','kommunikation',3,'low','symmetric',null,false),
('ko-07','Ein Tabu benennen','Offen aussprechen, was für dich nicht infrage kommt – ohne Begründungspflicht.','kommunikation',2,'low','symmetric',null,false),
('ko-08','Wunschzettel tauschen','Unabhängig voneinander drei Wünsche notieren und sie einander vorlesen.','kommunikation',2,'low','symmetric',null,false),
('ko-09','Schwierige Themen ansprechen','Ein Thema ansprechen, das dich schon länger beschäftigt, in einem ruhigen Moment außerhalb des Schlafzimmers.','kommunikation',2,'low','symmetric',null,false),
-- ── Initiative ─────────────────────────────────────────────────────────────
('in-01','Den ersten Schritt machen','Bewusst öfter selbst Nähe initiieren, statt darauf zu warten.','initiative',2,'low','switchable',null,false),
('in-02','Verführt werden','Dich einen Abend lang bewusst verführen lassen, ohne selbst die Führung zu übernehmen.','initiative',2,'low','directional',null,false),
('in-03','Überraschende Einladung','Die andere Person mit einer unerwarteten, eindeutigen Einladung überraschen.','initiative',2,'low','directional',null,false),
('in-04','Initiative abwechseln','Bewusst abwechseln, wer Nähe beginnt – zum Beispiel im Wochenrhythmus.','initiative',2,'low','switchable',null,false),
('in-05','Nonverbale Zeichen','Ein gemeinsames Zeichen vereinbaren, das Lust signalisiert, ohne Worte zu brauchen.','initiative',2,'low','symmetric',null,false),
('in-06','Langsames Werben','Einen ganzen Tag lang kleine Andeutungen und Gesten aufbauen, bevor ihr euch näherkommt.','initiative',2,'low','switchable',null,false),
('in-07','Direkt fragen','Lust direkt und unverblümt ansprechen, statt Umwege zu nehmen.','initiative',2,'low','symmetric',null,false),
('in-08','Morgens beginnen','Intimität am Morgen beginnen, wenn es sich für beide stimmig anfühlt.','initiative',2,'low','switchable',null,false),
('in-09','Spontane Momente','Spontane Nähe zulassen, auch wenn der Zeitpunkt ungeplant ist.','initiative',2,'low','symmetric',null,false),
-- ── Rollen und Dynamik ─────────────────────────────────────────────────────
('ro-01','Führen und folgen','In intimen Momenten bewusst eine führende oder folgende Rolle einnehmen.','rollen_dynamik',3,'low','directional',null,false),
('ro-02','Rollen tauschen','Die gewohnte Dynamik zwischen euch für einen Abend bewusst umkehren.','rollen_dynamik',3,'low','switchable',null,false),
('ro-03','Klare Ansagen','Eine Person gibt liebevoll, aber bestimmt den Ton an – im vorher vereinbarten Rahmen.','rollen_dynamik',3,'medium','directional','Vorher besprechen, was in Ordnung ist und was nicht. Ein Stoppsignal vereinbaren.',false),
('ro-04','Umsorgt werden','Sich einen Abend lang vollständig umsorgen und verwöhnen lassen.','rollen_dynamik',2,'low','directional',null,false),
('ro-05','Spielerischer Widerstand','Ein spielerisches Kräftemessen, bei dem beide jederzeit aussteigen können.','rollen_dynamik',3,'medium','switchable','Nur mit vereinbartem Stoppsignal. Ein Nein gilt sofort.',false),
('ro-06','Dienende Geste','Der anderen Person bewusst eine dienende, hingebungsvolle Geste schenken.','rollen_dynamik',3,'low','directional',null,false),
('ro-07','Dominanter Blickkontakt','Intensiven, fordernden Blickkontakt halten und die Spannung aushalten.','rollen_dynamik',2,'low','switchable',null,false),
('ro-08','Anweisungen geben','Der anderen Person sagen, was sie tun soll – und dabei ihre Grenzen respektieren.','rollen_dynamik',3,'medium','directional','Grenzen vorher klären. Anweisungen sind Angebote, keine Pflichten.',false),
('ro-09','Gleichberechtigte Nächte','Bewusst Abende ohne jede Rollendynamik gestalten – auf Augenhöhe, ohne Führung.','rollen_dynamik',1,'low','symmetric',null,false),
-- ── Langsames Ausprobieren ────────────────────────────────────────────────
('la-01','Nur der erste Schritt','Von etwas Neuem bewusst nur den allerersten kleinen Schritt ausprobieren.','langsames_ausprobieren',2,'low','symmetric',null,false),
('la-02','Probelauf mit Kleidung','Etwas Neues zunächst angezogen oder angedeutet durchspielen, bevor es ernst wird.','langsames_ausprobieren',2,'low','symmetric',null,false),
('la-03','Zeitlimit setzen','Neues zunächst nur für wenige Minuten ausprobieren und dann gemeinsam entscheiden, ob mehr passt.','langsames_ausprobieren',2,'low','symmetric',null,false),
('la-04','Erst erzählen, dann tun','Eine Idee erst ausführlich durchsprechen und frühestens beim nächsten Mal umsetzen.','langsames_ausprobieren',1,'low','symmetric',null,false),
('la-05','Vetorecht vereinbaren','Neues nur mit der Abmachung ausprobieren, dass jede Person jederzeit ohne Begründung abbrechen darf.','langsames_ausprobieren',1,'low','symmetric',null,false),
('la-06','Wiederholung vor Steigerung','Etwas Neues mehrfach in gleicher Intensität wiederholen, bevor ihr über eine Steigerung sprecht.','langsames_ausprobieren',2,'low','symmetric',null,false),
('la-07','Nachbesprechung einplanen','Nach jedem Experiment fest verabreden, in Ruhe darüber zu sprechen.','langsames_ausprobieren',1,'low','symmetric',null,false),
('la-08','Neugier-Liste','Eine gemeinsame Liste von Dingen führen, die ihr irgendwann einmal vorsichtig ausprobieren wollt.','langsames_ausprobieren',1,'low','symmetric',null,false),
('la-09','Ein Experiment pro Monat','Euch vornehmen, höchstens ein neues Experiment pro Monat zu wagen – ohne Druck.','langsames_ausprobieren',2,'low','symmetric',null,false),
-- ── Sinnliche Wahrnehmung ─────────────────────────────────────────────────
('si-01','Massage mit Öl','Eine ausgiebige Massage mit warmem Öl geben oder empfangen.','sinnliche_wahrnehmung',2,'low','switchable',null,false),
('si-02','Augen verbunden','Mit verbundenen Augen berührt werden und sich ganz auf das Spüren konzentrieren.','sinnliche_wahrnehmung',3,'medium','directional','Vorher ein Stoppsignal vereinbaren. Die Augenbinde darf jederzeit abgenommen werden.',false),
('si-03','Temperaturspiele','Mit warmen und kühlen Reizen experimentieren, etwa mit warmem Öl oder kühlen Gegenständen.','sinnliche_wahrnehmung',3,'medium','switchable','Extreme Temperaturen vermeiden. Vorher an einer kleinen Hautstelle testen.',false),
('si-04','Federleichte Berührung','Sehr langsame, kaum spürbare Berührungen mit Fingerspitzen oder weichen Materialien.','sinnliche_wahrnehmung',2,'low','switchable',null,false),
('si-05','Bewusstes Atmen','Den Atem der anderen Person wahrnehmen und die eigene Atmung darauf abstimmen.','sinnliche_wahrnehmung',1,'low','symmetric',null,false),
('si-06','Geräusche zulassen','Lust hörbar machen, statt Geräusche zu unterdrücken.','sinnliche_wahrnehmung',3,'low','symmetric',null,false),
('si-07','Düfte einsetzen','Mit Düften experimentieren, die ihr beide angenehm findet.','sinnliche_wahrnehmung',1,'low','symmetric',null,false),
('si-08','Ganzkörper-Erkundung','Den Körper der anderen Person langsam und vollständig erkunden, ohne Eile.','sinnliche_wahrnehmung',2,'low','switchable',null,false),
('si-09','Geschmack und Genuss','Etwas Essbares in intime Momente einbeziehen, etwa Früchte oder Schokolade.','sinnliche_wahrnehmung',2,'low','symmetric',null,false),
-- ── Kleidung und Inszenierung ─────────────────────────────────────────────
('kl-01','Besondere Wäsche','Wäsche tragen oder geschenkt bekommen, in der du dich attraktiv fühlst.','kleidung_inszenierung',2,'low','switchable',null,false),
('kl-02','Langsames Entkleiden','Einander langsam und bewusst entkleiden, als eigenes Ritual.','kleidung_inszenierung',2,'low','switchable',null,false),
('kl-03','Ein Outfit wünschen','Der anderen Person ein Outfit wünschen, das sie für euch beide trägt – wenn sie mag.','kleidung_inszenierung',2,'low','directional',null,false),
('kl-04','Angezogen bleiben','Intime Momente, bei denen bestimmte Kleidungsstücke bewusst anbleiben.','kleidung_inszenierung',2,'low','symmetric',null,false),
('kl-05','Gemeinsam einkaufen','Zusammen etwas aussuchen, das eine oder beide Personen für besondere Momente tragen.','kleidung_inszenierung',2,'low','symmetric',null,false),
('kl-06','Materialien spüren','Materialien wie Seide, Samt oder Spitze bewusst in Berührungen einbeziehen.','kleidung_inszenierung',2,'low','symmetric',null,false),
('kl-07','Sich zeigen','Sich der anderen Person in einem selbst gewählten Outfit bewusst präsentieren.','kleidung_inszenierung',3,'low','observer',null,false),
('kl-08','Alltagskleidung mit Geheimnis','Unter normaler Kleidung etwas Besonderes tragen, von dem nur ihr beide wisst.','kleidung_inszenierung',2,'low','symmetric',null,false),
('kl-09','Verkleidung light','Mit einem einzelnen Accessoire eine andere Ausstrahlung ausprobieren.','kleidung_inszenierung',2,'low','symmetric',null,false),
-- ── Fantasie und Rollenspiel ──────────────────────────────────────────────
('fa-01','Fremde im Café','Das Szenario spielen, euch an einem öffentlichen Ort zum ersten Mal zu begegnen.','fantasie_rollenspiel',3,'low','symmetric',null,false),
('fa-02','Eine Fantasie erzählen','Der anderen Person eine eigene Fantasie als Geschichte erzählen – nur zum Zuhören.','fantasie_rollenspiel',3,'low','symmetric',null,false),
('fa-03','Figuren erfinden','Gemeinsam zwei Figuren mit Namen und Hintergrund erfinden und einen Abend in ihren Rollen verbringen.','fantasie_rollenspiel',3,'low','symmetric',null,false),
('fa-04','Machtgefälle im Spiel','Ein klar abgesprochenes Rollenspiel mit Gefälle, etwa Vorgesetzte und Bewerbungsperson – als einvernehmliches Spiel unter Erwachsenen.','fantasie_rollenspiel',4,'medium','directional','Nur als klar vereinbartes Rollenspiel. Vorher Grenzen und ein Stoppsignal festlegen. Das Spiel endet sofort, wenn eine Person aussteigt.',true),
('fa-05','Historische Kulisse','Ein Rollenspiel in einer anderen Zeit oder Welt ansiedeln.','fantasie_rollenspiel',3,'low','symmetric',null,false),
('fa-06','Skript schreiben','Gemeinsam ein kurzes Drehbuch für eine Szene schreiben, bevor ihr sie spielt.','fantasie_rollenspiel',3,'low','symmetric',null,false),
('fa-07','Nur Stimme und Worte','Ein Rollenspiel, das ausschließlich über Sprache stattfindet, ohne Berührung.','fantasie_rollenspiel',3,'low','symmetric',null,false),
('fa-08','Verführungsszene','Eine klassische Verführungsszene nachspielen, in der eine Person umworben wird.','fantasie_rollenspiel',3,'low','directional',null,false),
('fa-09','Fantasie bleibt Fantasie','Über Fantasien sprechen, die ihr bewusst niemals umsetzen wollt – und das gemeinsam würdigen.','fantasie_rollenspiel',3,'low','symmetric',null,false),
-- ── Beobachten und gesehen werden ─────────────────────────────────────────
('be-01','Beim Anziehen zusehen','Der anderen Person bewusst beim An- oder Umziehen zusehen.','beobachten_gesehen_werden',2,'low','observer',null,false),
('be-02','Sich berühren lassen sehen','Zusehen oder gesehen werden, während sich eine Person selbst berührt.','beobachten_gesehen_werden',4,'low','observer',null,false),
('be-03','Spiegelmomente','Intime Momente vor einem Spiegel erleben und euch dabei betrachten.','beobachten_gesehen_werden',3,'low','symmetric',null,false),
('be-04','Erzählen statt zeigen','Der anderen Person detailliert beschreiben, was du gerade siehst und was es mit dir macht.','beobachten_gesehen_werden',3,'low','observer',null,false),
('be-05','Blicke im Alltag','Im Alltag bewusst lange, vielsagende Blicke austauschen, von denen nur ihr wisst.','beobachten_gesehen_werden',1,'low','symmetric',null,false),
('be-06','Eine Person führt, eine sieht zu','Eine Person gestaltet einen Moment nur für die Augen der anderen.','beobachten_gesehen_werden',3,'low','observer',null,false),
('be-07','Fotos nur für euch','Ästhetische Fotos voneinander machen, die ausschließlich auf einem gemeinsam vereinbarten, gesicherten Gerät bleiben.','beobachten_gesehen_werden',4,'high','switchable','Nur mit ausdrücklicher Zustimmung. Vorher klären, wo Aufnahmen gespeichert werden und wann sie gelöscht werden. Jede Person darf jederzeit die Löschung verlangen.',true),
('be-08','Gesehen werden aushalten','Dich betrachten lassen, ohne dich zu verstecken – so lange es sich gut anfühlt.','beobachten_gesehen_werden',3,'low','observer',null,false),
('be-09','Beschreiben, was gefällt','Laut aussprechen, was dir am Körper der anderen Person besonders gefällt.','beobachten_gesehen_werden',2,'low','symmetric',null,false),
-- ── Kontrolle und Abgabe von Kontrolle ────────────────────────────────────
('kn-01','Hände still halten','Vereinbaren, dass eine Person die Hände still hält, ohne Fixierung – jederzeit beendbar.','kontrolle',3,'medium','directional','Nur mit Stoppsignal. Keine Fixierung, die Person kann sich jederzeit frei bewegen.',false),
('kn-02','Sanftes Festhalten','Mit sanftem Festhalten der Handgelenke experimentieren.','kontrolle',3,'medium','directional','Vorher besprechen, was in Ordnung ist. Ein Stoppsignal vereinbaren. Sofort lösen, wenn gewünscht.',true),
('kn-03','Tempo bestimmen lassen','Einer Person für eine vereinbarte Zeit das Tempo überlassen.','kontrolle',3,'medium','directional','Die abgebende Person darf jederzeit eingreifen oder abbrechen.',false),
('kn-04','Weiche Fesseln','Mit weichen, leicht lösbaren Fesseln experimentieren, etwa einem Seidentuch.','kontrolle',4,'high','directional','Nur mit klarem Stoppsignal. Nie am Hals. Immer eine Schere oder schnelle Lösemöglichkeit bereithalten. Nie eine gefesselte Person allein lassen.',true),
('kn-05','Entscheidungen abgeben','Einen Abend lang kleine Entscheidungen bewusst der anderen Person überlassen.','kontrolle',2,'low','directional',null,false),
('kn-06','Warten müssen','Vereinbarte Momente des Wartens und der Vorfreude aushalten, bevor Berührung erlaubt ist.','kontrolle',3,'medium','directional','Wartezeiten vorher vereinbaren. Jede Person darf jederzeit aussteigen.',false),
('kn-07','Kontrolle zurückerobern','Ein Spiel, bei dem die Führung mehrmals bewusst wechselt.','kontrolle',3,'medium','switchable','Wechsel und Grenzen vorher besprechen.',false),
('kn-08','Regeln für einen Abend','Für einen Abend spielerische Regeln vereinbaren, die jederzeit widerrufbar sind.','kontrolle',3,'medium','directional','Regeln sind ein Spiel, keine Pflichten. Jede Regel endet sofort auf Wunsch.',false),
('kn-09','Nachgeben genießen','Bewusst erleben, wie es sich anfühlt, die Kontrolle vertrauensvoll abzugeben.','kontrolle',3,'medium','directional','Nur so weit, wie es sich sicher anfühlt. Stoppsignal vereinbaren.',false),
-- ── Orte und Situationen ──────────────────────────────────────────────────
('or-01','Anderes Zimmer','Intimität bewusst in einem anderen Raum eurer Wohnung erleben als gewohnt.','orte_situationen',2,'low','symmetric',null,false),
('or-02','Hotelnacht','Eine Nacht in einem Hotel verbringen, nur um Zeit füreinander zu haben.','orte_situationen',2,'low','symmetric',null,false),
('or-03','Eigener Garten oder Balkon','Nähe im geschützten, nicht einsehbaren Außenbereich des eigenen Zuhauses erleben.','orte_situationen',3,'medium','symmetric','Nur an Orten, die wirklich privat und nicht einsehbar sind. Die Privatsphäre unbeteiligter Personen bleibt unantastbar.',false),
('or-04','Tageslicht','Intime Momente bewusst bei Tageslicht statt im Dunkeln erleben.','orte_situationen',2,'low','symmetric',null,false),
('or-05','Spontan zuhause','Einen ungewöhnlichen Moment im Alltag nutzen, wenn ihr ungestört seid.','orte_situationen',2,'low','symmetric',null,false),
('or-06','Urlaubs-Ich','Im Urlaub eine freiere, mutigere Version von euch ausprobieren.','orte_situationen',2,'low','symmetric',null,false),
('or-07','Auto mit Privatsphäre','Nähe im eigenen Auto an einem abgelegenen, privaten Ort – im rechtlichen Rahmen.','orte_situationen',3,'medium','symmetric','Nur an wirklich privaten Orten. Öffentliches Ärgernis und die Rechte Dritter sind tabu.',false),
('or-08','Küche statt Schlafzimmer','Spontane Nähe an einem alltäglichen Ort in der eigenen Wohnung.','orte_situationen',2,'low','symmetric',null,false),
('or-09','Bett neu gedacht','Das Schlafzimmer einmal komplett anders herrichten, als wäre es ein fremder Ort.','orte_situationen',1,'low','symmetric',null,false),
-- ── Hilfsmittel ───────────────────────────────────────────────────────────
('hi-01','Massageöl und Kerzen','Klassische Hilfsmittel wie Öl und Massagekerzen einsetzen.','hilfsmittel',2,'low','symmetric',null,false),
('hi-02','Erstes Toy gemeinsam aussuchen','Zusammen ein erstes Toy aussuchen, das euch beide neugierig macht.','hilfsmittel',3,'low','symmetric',null,false),
('hi-03','Toy in Partnermomente einbeziehen','Ein Toy nicht nur allein, sondern gemeinsam verwenden.','hilfsmittel',3,'low','symmetric',null,false),
('hi-04','Augenbinde','Eine weiche Augenbinde als einfaches Hilfsmittel ausprobieren.','hilfsmittel',3,'medium','directional','Jederzeit abnehmbar. Stoppsignal vereinbaren.',false),
('hi-05','Federn und Materialien','Weiche Materialien wie Federn oder Pinsel für Berührungen verwenden.','hilfsmittel',2,'low','switchable',null,false),
('hi-06','Gleitgel entdecken','Verschiedene Gleitgele ausprobieren und herausfinden, was sich gut anfühlt.','hilfsmittel',2,'low','symmetric',null,false),
('hi-07','Gemeinsame Schublade','Eine gemeinsame, private Schublade für eure Hilfsmittel einrichten.','hilfsmittel',2,'low','symmetric',null,false),
('hi-08','App-gesteuertes Toy','Ein Toy ausprobieren, das die andere Person steuern kann.','hilfsmittel',4,'medium','directional','Steuerung nur mit laufender Zustimmung. Jederzeit beendbar.',false),
('hi-09','Qualität vor Menge','Bewusst in ein hochwertiges Hilfsmittel investieren statt in viele günstige.','hilfsmittel',2,'low','symmetric',null,false),
-- ── Intensität ────────────────────────────────────────────────────────────
('it-01','Sehr langsam','Einen intimen Moment bewusst auf ein Vielfaches der üblichen Dauer ausdehnen.','intensitaet',2,'low','symmetric',null,false),
('it-02','Intensiver Blickkontakt','Während intimer Momente durchgehend Blickkontakt halten.','intensitaet',3,'low','symmetric',null,false),
('it-03','Fester Griff','Mit festeren, greifenden Berührungen experimentieren, wo beide es mögen.','intensitaet',3,'medium','switchable','Vorher besprechen, wo und wie fest. Sofort lockern, wenn gewünscht.',false),
('it-04','Kratzen und Spuren','Leichtes Kratzen oder sichtbare Spuren, wenn beide das ausdrücklich möchten.','intensitaet',4,'medium','switchable','Nur mit ausdrücklicher Zustimmung. Vorher klären, ob Spuren in Ordnung sind. Gesicht und Hals aussparen.',true),
('it-05','Leichte Klapse','Leichte Klapse an unempfindlichen Stellen, wenn beide es ausdrücklich möchten.','intensitaet',4,'high','directional','Nur nach ausdrücklicher Vereinbarung. Mit sehr geringer Intensität beginnen. Stoppsignal vereinbaren. Nieren, Wirbelsäule, Gesicht und Hals sind tabu.',true),
('it-06','Pausen als Steigerung','Bewusste Unterbrechungen einbauen, um Spannung aufzubauen.','intensitaet',3,'low','symmetric',null,false),
('it-07','Mehrfache Wellen','Erregung mehrfach auf- und abklingen lassen, bevor ihr sie auflöst.','intensitaet',3,'low','symmetric',null,false),
('it-08','Flüstern und Sprache','Intensität über Worte steigern – von zärtlich bis fordernd, wie ihr es mögt.','intensitaet',3,'low','symmetric',null,false),
('it-09','Nur ein Körperteil','Einen ganzen Moment ausschließlich einer einzigen Körperregion widmen.','intensitaet',2,'low','switchable',null,false),
-- ── Neues ausprobieren ────────────────────────────────────────────────────
('ne-01','Eine neue Position','Eine für euch neue Position in Ruhe ausprobieren.','neues_ausprobieren',2,'low','symmetric',null,false),
('ne-02','Tageszeit wechseln','Intimität zu einer völlig ungewohnten Tageszeit erleben.','neues_ausprobieren',1,'low','symmetric',null,false),
('ne-03','Reihenfolge umdrehen','Den gewohnten Ablauf intimer Momente bewusst umstellen.','neues_ausprobieren',2,'low','symmetric',null,false),
('ne-04','Karte ziehen','Aus euren gemeinsamen Matches zufällig eines ziehen und darüber sprechen.','neues_ausprobieren',2,'low','symmetric',null,false),
('ne-05','Etwas nur einmal testen','Vereinbaren, etwas genau einmal zu testen und danach ehrlich Bilanz zu ziehen.','neues_ausprobieren',2,'low','symmetric',null,false),
('ne-06','Workshop oder Buch','Gemeinsam ein Buch oder einen seriösen Kurs zu einem Thema entdecken, das euch interessiert.','neues_ausprobieren',2,'low','symmetric',null,false),
('ne-07','Kleine Mutprobe','Etwas ausprobieren, das euch beide leicht nervös macht – im sicheren Rahmen.','neues_ausprobieren',3,'low','symmetric',null,false),
('ne-08','Altbewährtes neu','Etwas, das ihr lange nicht mehr gemacht habt, bewusst wiederholen.','neues_ausprobieren',1,'low','symmetric',null,false),
('ne-09','Wunsch der anderen Person','Einen Wunsch der anderen Person ausprobieren, dem du neugierig, aber unsicher gegenüberstehst – nur wenn du wirklich möchtest.','neues_ausprobieren',3,'low','symmetric',null,false),
-- ── Digitale Nähe ─────────────────────────────────────────────────────────
('di-01','Nachrichten mit Andeutung','Tagsüber Nachrichten mit eindeutigen Andeutungen austauschen.','digitale_naehe',2,'low','symmetric',null,false),
('di-02','Sprachnachricht','Der anderen Person eine persönliche, intime Sprachnachricht schicken.','digitale_naehe',3,'medium','switchable','Nur über Kanäle, denen ihr beide vertraut. Vorher klären, ob solche Nachrichten willkommen sind.',false),
('di-03','Gemeinsame Wunschliste','Eine private digitale Liste mit Ideen und Wünschen führen.','digitale_naehe',2,'low','symmetric',null,false),
('di-04','Videoanruf auf Distanz','Bei räumlicher Trennung Nähe über einen Videoanruf herstellen.','digitale_naehe',3,'medium','symmetric','Nur über vertrauenswürdige, private Verbindungen. Keine Aufnahmen ohne ausdrückliche Zustimmung beider Personen.',false),
('di-05','Countdown bis zum Wiedersehen','Vor einem Wiedersehen die Vorfreude gezielt mit Nachrichten steigern.','digitale_naehe',2,'low','symmetric',null,false),
('di-06','Digitale Verabredung','Einen festen digitalen Termin nur für euch zwei vereinbaren, wenn ihr getrennt seid.','digitale_naehe',1,'low','symmetric',null,false),
('di-07','Text statt Bild','Erotische Spannung bewusst nur über Text aufbauen, ohne Bilder.','digitale_naehe',3,'low','symmetric',null,false),
('di-08','Gemeinsame Playlist','Eine Playlist pflegen, die für euch beide mit besonderen Momenten verbunden ist.','digitale_naehe',1,'low','symmetric',null,false),
('di-09','Digitale Pause','Bewusst vereinbaren, wann digitale Reize pausieren und echte Nähe Vorrang hat.','digitale_naehe',1,'low','symmetric',null,false),
-- ── Nachsorge und Nähe danach ─────────────────────────────────────────────
('ns-01','Kuscheln danach','Nach intimen Momenten bewusst Zeit für Nähe ohne Ziel einplanen.','nachsorge',1,'low','symmetric',null,false),
('ns-02','Wasser und Wärme','Nach intensiven Momenten füreinander sorgen: Wasser, Decke, Wärme.','nachsorge',1,'low','symmetric',null,false),
('ns-03','Kurzes Nachgespräch','Kurz teilen, wie es euch geht – ohne Bewertung, ohne Analyse.','nachsorge',1,'low','symmetric',null,false),
('ns-04','Stille zulassen','Nach intensiven Momenten gemeinsam schweigen dürfen, ohne dass es komisch ist.','nachsorge',1,'low','symmetric',null,false),
('ns-05','Nachsorge vereinbaren','Vor intensiveren Experimenten festlegen, was ihr danach voneinander braucht.','nachsorge',2,'low','symmetric',null,false),
('ns-06','Am nächsten Tag nachfragen','Am Tag danach noch einmal ehrlich nachfragen, wie es der anderen Person geht.','nachsorge',1,'low','symmetric',null,false),
('ns-07','Körperkontakt halten','Nach dem Höhepunkt in Körperkontakt bleiben, statt direkt aufzustehen.','nachsorge',1,'low','symmetric',null,false),
('ns-08','Dankbarkeit aussprechen','Der anderen Person sagen, wofür du in diesem Moment dankbar bist.','nachsorge',1,'low','symmetric',null,false),
('ns-09','Emotionale Nachwirkungen','Darüber sprechen dürfen, wenn ein intensiver Moment unerwartete Gefühle auslöst.','nachsorge',2,'low','symmetric',null,false),
-- ── Grenzen und Tabus ─────────────────────────────────────────────────────
('gr-01','Klare No-Gos benennen','Unabhängig voneinander festhalten, was für euch grundsätzlich nicht infrage kommt.','grenzen_tabus',1,'low','symmetric',null,false),
('gr-02','Grenzen ohne Begründung','Vereinbaren, dass Grenzen niemals begründet werden müssen.','grenzen_tabus',1,'low','symmetric',null,false),
('gr-03','Stoppsignal etablieren','Ein gemeinsames Stoppsignal festlegen, das immer und sofort gilt.','grenzen_tabus',1,'low','symmetric',null,false),
('gr-04','Grenzen dürfen sich ändern','Anerkennen, dass sich Grenzen jederzeit verschieben dürfen – in beide Richtungen.','grenzen_tabus',1,'low','symmetric',null,false),
('gr-05','Körperliche Tabuzonen','Körperstellen benennen, die nicht oder nur auf bestimmte Weise berührt werden sollen.','grenzen_tabus',2,'low','symmetric',null,false),
('gr-06','Emotionale Grenzen','Auch emotionale Grenzen benennen, etwa Worte oder Szenarien, die verletzen würden.','grenzen_tabus',2,'low','symmetric',null,false),
('gr-07','Nein üben','Bewusst üben, Nein zu sagen und ein Nein wohlwollend anzunehmen.','grenzen_tabus',1,'low','symmetric',null,false),
('gr-08','Check vor Neuem','Vor jedem neuen Experiment die Grenzen beider Personen aktiv abfragen.','grenzen_tabus',1,'low','symmetric',null,false),
('gr-09','Vergangenes respektieren','Respektieren, wenn bestimmte Themen wegen früherer Erfahrungen tabu sind – ohne Nachbohren.','grenzen_tabus',2,'low','symmetric',null,false),
-- ── Gesprächsimpulse ──────────────────────────────────────────────────────
('gi-01','Begehrt fühlen','Darüber sprechen, wodurch ihr euch besonders begehrt fühlt.','gespraechsimpulse',1,'low','symmetric',null,false),
('gi-02','Sicherheit erkennen','Woran merkt ihr jeweils, dass ihr euch sicher fühlt?','gespraechsimpulse',1,'low','symmetric',null,false),
('gi-03','Schönste Erinnerung','Von eurem schönsten gemeinsamen intimen Moment erzählen.','gespraechsimpulse',2,'low','symmetric',null,false),
('gi-04','Erste Anziehung','Erzählen, was euch am Anfang aneinander angezogen hat.','gespraechsimpulse',1,'low','symmetric',null,false),
('gi-05','Alltag und Lust','Darüber sprechen, wie Stress und Alltag eure Lust beeinflussen.','gespraechsimpulse',1,'low','symmetric',null,false),
('gi-06','Gutes Nachfragen','Was bedeutet für euch gutes, respektvolles Nachfragen?','gespraechsimpulse',1,'low','symmetric',null,false),
('gi-07','Zuneigung im Alltag','Welche Form von Zuneigung fehlt im Alltag manchmal?','gespraechsimpulse',1,'low','symmetric',null,false),
('gi-08','Nach schwierigen Momenten','Wie könnt ihr nach einem schwierigen Moment wieder Nähe herstellen?','gespraechsimpulse',1,'low','symmetric',null,false),
('gi-09','Zukunftsbild','Wie wünscht ihr euch eure Intimität in fünf Jahren?','gespraechsimpulse',1,'low','symmetric',null,false);

-- allowed_roles per role model
update public.question_cards set allowed_roles = case role_model
  when 'symmetric' then array['not_relevant']
  when 'not_relevant' then array['not_relevant']
  when 'directional' then array['initiating','receiving','switching','both']
  when 'observer' then array['observing','receiving','switching','both']
  when 'switchable' then array['initiating','receiving','switching','both']
end;
